env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  React: writable
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
  - prettier
rules:
  prettier/prettier:
    - error
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
